version: '3'

services:
  redis:
    build:
      dockerfile: fly/redis/Dockerfile
      context: .
    ports:
      - '6379:6379'
      - '6380:6380'
      - '6381:6381'
    environment:
      PAGE_DATA_REDIS_PW: '${DEV_REDIS_PW}'
      MAL_CACHE_REDIS_PW: '${DEV_REDIS_PW}'
      SEARCH_AND_SEASONAL_REDIS_PW: '${DEV_REDIS_PW}'
    volumes:
      - redis-data:/data
    restart: always

  server:
    build:
      dockerfile: server/Dockerfile
      context: .
    ports:
      - '3001:3001'
    depends_on:
      - redis
    environment:
      PAGE_DATA_REDIS_URL: 'redis://:${DEV_REDIS_PW}@redis:6379'
      MAL_CACHE_REDIS_URL: 'redis://:${DEV_REDIS_PW}@redis:6380'
      SEARCH_AND_SEASONAL_REDIS_URL: 'redis://:${DEV_REDIS_PW}@redis:6381'
    env_file:
      - server/.env
    volumes:
      - ./server:/app
      - ./node_modules:/app/node_modules

  next-frontend:
    build:
      dockerfile: next-frontend/Dockerfile.dev
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - server
    environment:
      API_URL: http://server:3001
      NEXT_PUBLIC_API_URL: http://localhost:3001
    env_file:
      - next-frontend/.env.local
    volumes:
      - ./next-frontend:/app
      - ./node_modules:/app/node_modules

volumes:
  redis-data:
