version: '3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: always

  mal-cache-redis:
    image: 'redis:alpine'
    ports:
      - '6380:6379'
    volumes:
      - mal-cache-redis-data:/data
    restart: always

  search-and-seasonal-redis:
    image: 'redis:alpine'
    ports:
      - '6381:6379'
    volumes:
      - search-and-seasonal-redis-data:/data
    restart: always

  server:
    build:
      dockerfile: server/Dockerfile
      context: .
    ports:
      - '3001:3001'
    depends_on:
      - redis
      - mal-cache-redis
      - search-and-seasonal-redis
    environment:
      NODE_ENV: 'development'
      APP_ENV: 'dev'
      PM2_ENV: 'dev'
      REDIS_URL: 'redis://redis:6379'
      MAL_CACHE_REDIS_URL: 'redis://mal-cache-redis:6379'
      SEARCH_AND_SEASONAL_REDIS_URL: 'redis://search-and-seasonal-redis:6379'
    env_file:
      - server/.env
    command: ['yarn', 'dev']
    volumes:
      - ./server:/app
      - server-deps:/app/node_modules

  next-frontend:
    build:
      dockerfile: next-frontend/Dockerfile.dev
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - server
    environment:
      NODE_ENV: 'development'
      APP_ENV: 'dev'
    env_file:
      - next-frontend/.env.local
    volumes:
      - ./next-frontend:/app
      - next-frontend-deps:/app/node_modules

volumes:
  server-deps:
  next-frontend-deps:
  redis-data:
  mal-cache-redis-data:
  search-and-seasonal-redis-data:
