# fly.toml app configuration file generated for related-anime-server on 2023-06-23T20:53:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "related-anime-server"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 512

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "prod"
  AWS_DYNAMODB_TABLE_NAME = "mal-cache"
  AWS_REGION = "us-east-1"
  NODE_ENV = "production"
  PORT = "3001"

[[services]]
  protocol = "tcp"
  internal_port = 3001

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 1000000
    soft_limit = 20
